### ISSUE TITLE
#pretrain model

### ISSUE THREAD

**Issue by gnorZgnoD** [JusperLee/TDANet#10]
Hi, will you upload the pretrain model recently?

**Comment by JusperLee** [comment]
I should be uploading all the pretrained models tonight.

**Comment by JusperLee** [comment]
I've provided two pre-trained models trained on the LRS2 dataset. You can find them on the Hugging Face Model Hub at the following URLs:

1. [TDANetBest-2ms-LRS2](https://huggingface.co/JusperLee/TDANetBest-2ms-LRS2)
2. [TDANetBest-4ms-LRS2](https://huggingface.co/JusperLee/TDANetBest-4ms-LRS2)

To utilize these models, you can use the following code:

```python
import os
import torch
import look2hear.models

os.environ['CUDA_VISIBLE_DEVICES'] = "0"

model = look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()
test_data = torch.randn(1, 1, 16000).cuda()
out = model(test_data)
print(out.shape)
```

Please let me know if you encounter any issues or if there's anything else I can assist you with

**Comment by gnorZgnoD** [comment]
So, if i wanna use the TDANetBest-2ms-LRS2 pretrain model, i need to add the code you provided to my train.py and then run it, right?

**Comment by JusperLee** [comment]
Yes.

**Comment by gnorZgnoD** [comment]
I use the trainer.fit to reload the model, so i need the ckpt version of a pretrain model, could you please provide the ckpt version of the TDANetBest-2ms-LRS2 pretrain model? tks.

**Comment by JusperLee** [comment]
I can provide the original ckpt for resuming. I'll upload it soon.

**Comment by gnorZgnoD** [comment]
Okay, i‘m looking forward for your upload.

**Comment by gnorZgnoD** [comment]
Hi, Jusper, when i use the checkpoint you provided, i encountered the following issue, how could i sovle it?
![image](https://github.com/JusperLee/TDANet/assets/105347776/e6e2c29d-2881-494a-8ca1-08142caa63ad)

**Comment by Linghuxc** [comment]
@JusperLee hello Jusper, I try to use your pretrained model in huggingface, but because of my net, I can only download and modify the model path manually.
But he will make the following mistakes:
![image](https://github.com/JusperLee/TDANet/assets/128498268/1f44930d-65cf-4a4c-9637-b2a784743f24)
In this line of code, there is no way to direct the load directory, but load pytorch_model.bin will cause dimension mismatch again
Can you help me?

**Comment by JusperLee** [comment]
@Linghuxc You remove the ". /" symbol.

**Comment by JusperLee** [comment]
> @JusperLee hello Jusper, I try to use your pretrained model in huggingface, but because of my net, I can only download and modify the model path manually. But he will make the following mistakes: ![image](https://private-user-images.githubusercontent.com/128498268/320349528-1f44930d-65cf-4a4c-9637-b2a784743f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTg0MTgsIm5iZiI6MTcxMjU1ODExOCwicGF0aCI6Ii8xMjg0OTgyNjgvMzIwMzQ5NTI4LTFmNDQ5MzBkLTY1Y2YtNGE0Yy05NjM3LWIyYTc4NDc0M2YyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNjM1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJmNDA2ZGFlNjIyYWQ3NWMxODIzNDA4MzQyMmRmMjgwODc3MzI2MzE4ZDBmYzI2MDgxM2ZiOTY0ODI1YTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmVulormKHjmIyyI9t7F_iADeYTd5OMdWPh33CWXBH4) In this line of code, there is no way to direct the load directory, but load pytorch_model.bin will cause dimension mismatch again Can you help me?

model =  look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()

**Comment by Linghuxc** [comment]
> > @JusperLee hello Jusper, I try to use your pretrained model in huggingface, but because of my net, I can only download and modify the model path manually. But he will make the following mistakes: ![image](https://private-user-images.githubusercontent.com/128498268/320349528-1f44930d-65cf-4a4c-9637-b2a784743f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTg0MTgsIm5iZiI6MTcxMjU1ODExOCwicGF0aCI6Ii8xMjg0OTgyNjgvMzIwMzQ5NTI4LTFmNDQ5MzBkLTY1Y2YtNGE0Yy05NjM3LWIyYTc4NDc0M2YyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNjM1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJmNDA2ZGFlNjIyYWQ3NWMxODIzNDA4MzQyMmRmMjgwODc3MzI2MzE4ZDBmYzI2MDgxM2ZiOTY0ODI1YTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmVulormKHjmIyyI9t7F_iADeYTd5OMdWPh33CWXBH4) In this line of code, there is no way to direct the load directory, but load pytorch_model.bin will cause dimension mismatch again Can you help me?
> 
> model = look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()

I know what you mean. However, this required the server to download the model from huggingface, but due to network problems I had to download it manually from the page and then upload it to my server side
![image](https://github.com/JusperLee/TDANet/assets/128498268/9d731106-bb12-4b81-9183-ea9bde1f5f2f)

**Comment by Linghuxc** [comment]
@JusperLee Hi, I use the model"pytorch_model.bin" ,such an error has occurred:
![image](https://github.com/JusperLee/TDANet/assets/128498268/7b076b4a-1901-45df-ac60-e81b58124bc9)
