### ISSUE TITLE
voice separation

### ISSUE THREAD

**Issue by Aoaoni** [JusperLee/TDANet#11]
Hi, I'd like to ask if this can be used for voice separation of more than four people and with longer duration.

**Comment by JusperLee** [comment]
Yes, it is indeed possible to use this model for voice separation involving more than four people and for longer durations. However, to effectively handle such scenarios, you will need to make adjustments to the model's output as well as modify some parameters. These adjustments are essential to ensure that the model can manage the increased complexity and variability associated with separating a larger number of voices over an extended period.
