### ISSUE TITLE
Interface for Audio Processing

### ISSUE THREAD

**Issue by Susukerow45** [JusperLee/TDANet#14]
Hello I like your project and I would like to try it in action, but I am not good with Pyton, and wanted to ask if there are ready separators for wav for example, or if there are any third-party priojects that can help me with this, thanks in advance.

**Comment by jjandnn** [comment]
@Susukerow45 
import os
import sys
import torch
import torchaudio
import look2hear.models

os.environ['CUDA_VISIBLE_DEVICES'] = "0"

model =  look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()
# model =  look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-4ms-LRS2").cuda() # 模型2

audio = sys.path[0] + '\\sample.wav'

# 将 wav 文件转换为采样率为 16000 Hz 的采样数组
data, sample_rate = torchaudio.load(audio)
new_sample_rate, channel = 16000, 0
transformed = torchaudio.transforms.Resample(sample_rate, new_sample_rate)(data[channel,:].view(1,-1))

# 将采样数组转换为形状为 (1, 1, 16000) 的张量
X = torch.Tensor(transformed).cuda()

# 分离
X = model(X)

torchaudio.save(sys.path[0] + '\\new1.wav', X[:, 0, :].detach().cpu(), new_sample_rate)
torchaudio.save(sys.path[0] + '\\new2.wav', X[:, 1, :].detach().cpu(), new_sample_rate)
print('说话人分离完成')

**Comment by jjandnn** [comment]
`import os
import sys
import torch
import torchaudio
import look2hear.models

os.environ['CUDA_VISIBLE_DEVICES'] = "0"

model =  look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()
# model =  look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-4ms-LRS2").cuda()

audio = sys.path[0] + '\\sample.wav'

# 将 wav 文件转换为采样率为 16000 Hz 的采样数组
data, sample_rate = torchaudio.load(audio)
new_sample_rate, channel = 16000, 0
transformed = torchaudio.transforms.Resample(sample_rate, new_sample_rate)(data[channel,:].view(1,-1))

# 将采样数组移到gpu上
X = torch.Tensor(transformed).cuda()

# 分离
X = model(X)

torchaudio.save(sys.path[0] + '\\new1.wav', X[:, 0, :].detach().cpu(), new_sample_rate)
torchaudio.save(sys.path[0] + '\\new2.wav', X[:, 1, :].detach().cpu(), new_sample_rate)
print('说话人分离完成')`
@Susukerow45

**Comment by Susukerow45** [comment]
@jjandnn 
Thanks for exsample, but i can't get it work, they just show me error 

    X = model(X)
TypeError: 'str' object is not callable
