### ISSUE TITLE
Threshold By Loss

### ISSUE THREAD

**Issue by gnorZgnoD** [JusperLee/TDANet#17]
Hi, author:
  How will the threshold_byloss affect the performance of your tdanet? Why threshold_byloss of train is true, and threshold_byloss of val is false?
![image](https://github.com/JusperLee/TDANet/assets/105347776/b59a23cd-096d-4d1c-96e6-ae98601ef5c5)

**Comment by JusperLee** [comment]
Using this during training will suppress results with SI-SNR > 30 dB, which will somewhat focus the model on poorly trained data. When testing, adding this will allow results over 30 dB to be truncated to 30 dB.

**Comment by gnorZgnoD** [comment]
Thank for your prompt reply!
