### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by Linghuxc** [JusperLee/TDANet#18]
@JusperLee  您好，我现在成功使用了您提供的预训练模型，并且可以成功加载。我尝试输入一个带噪语音进行分离，但是会在我的4090GPU上爆显存。是否我输入语音的方式不对？希望能得到您的帮助！
![image](https://github.com/JusperLee/TDANet/assets/128498268/d44effe7-7e46-4c3f-a224-65cf6c9d9f89)

**Comment by JusperLee** [comment]
你的音频大概多长呢？

**Comment by Linghuxc** [comment]
7秒左右

**Comment by Linghuxc** [comment]
> 你的音频大概多长呢？

7s左右

**Comment by JusperLee** [comment]
那不应该会爆显存。
你可以添加
with torch.no_grad():
    # 你的推理代码

**Comment by Linghuxc** [comment]
非常感谢您！这很有用，我现在已经可以使用这个进行推理，后续我想在进行进一步的微调。
如果不加入”with torch.no_grad():“，我发现如果使用"4ms"的模型，加载大概15000Mib的显存，是可以正常推理；如果是使用"2ms"，则会超过24G。增加显存的网络主要是这个：
![image](https://github.com/JusperLee/TDANet/assets/128498268/08e0b887-b4b1-4be3-8596-ec3477499593)
当然，现在使用with torch.no_grad():后就不会出现这个问题了，非常非常感谢您！

**Comment by Linghuxc** [comment]
@JusperLee 还有一个问题请问您，因为我以前没有接触过分离或增强的模型。请问out输出之后的形状为：（1, 2, T），那我是否按照第1维度分开之后就得到了两个分离后的语音？例如这样：
![image](https://github.com/JusperLee/TDANet/assets/128498268/0dfc2914-8893-476d-9477-0af425ce09be)
我这样是可以得到分离的语音，但我不知道这样做是否合理或者是否会影响分离的效果？

**Comment by JusperLee** [comment]
应该是第二个维度

**Comment by Linghuxc** [comment]
> 应该是第二个维度,（1, 2, T）把这个2拆开

对，我就是这样做的，已经得到了分离后的音频，非常感谢！
