### ISSUE TITLE
Audio loading example?

### ISSUE THREAD

**Issue by miraodasilva** [JusperLee/TDANet#20]
Could you please provide an example of loading a mixture and doing inference on it? The example on the README only uses torch.randn aka a random tensor rather than a real audio.

I'm trying to do so like this:
```python
mix, sr = torchaudio.load("audio_mix.wav")
transform = torchaudio.transforms.Resample(sr, 16_000)
mix = transform(mix)
mix = mix.view(1, 1, -1)
model = look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()
est_sources = model(mix.cuda())
torchaudio.save("audio1sep.wav", est_sources[:, 0, :].detach().cpu(), 16_000)
torchaudio.save("audio2sep.wav", est_sources[:, 1, :].detach().cpu(), 16_000)
```

But the outputs come out sounding really bad. Am I doing something wrong?

Thanks a lot in advance :)

**Comment by JusperLee** [comment]
Hi,

I have tested your code using the provided [audio_mix.wav](https://github.com/JusperLee/TDANet/blob/main/audio_mix.wav), and I believe that your code is correct.

The reason for the suboptimal separation quality is that the pre-trained model we provide was trained on the LRS2 dataset, which may not cover all possible scenarios.

If you intend to use the model in specific scenarios, I recommend fine-tuning the model based on the pre-trained weights to achieve better performance.

Please feel free to reach out if you have any further questions or concerns. I'm always happy to discuss and assist you.

Best regards, Kai
