### ISSUE TITLE
Inquiry Regarding Model Usage in Testing

### ISSUE THREAD

**Issue by Saleha12345** [JusperLee/TDANet#24]
Could you please clarify why a pre-trained model is being utilized for testing? Is there a specific reason the trained model isn't being employed in audio_test.py? Additionally, could you provide guidance on how to integrate the trained model into the testing file?"

**Comment by JusperLee** [comment]
You may have misunderstood audio_test.py, this code uses pre-trained models for quick validation using the weights we provide. You can also use your own trained model.
