### ISSUE TITLE
关于MACs指标的计算

### ISSUE THREAD

**Issue by chiexplorer** [JusperLee/TDANet#25]
根据我的了解，MACs指标的计算与时间无关，但我注意到Table 3中MACs的单位是G/s，请问这是否表示将thop计算得到的MACs值除以音频的持续时长？

**Comment by JusperLee** [comment]
我是输入的长度为一秒16khz的音频，这么测试的。

**Comment by chiexplorer** [comment]
我明白了，感谢解答
