### ISSUE TITLE
你好，想请问一下，模型参数量和计算量与paper未对应的问题

### ISSUE THREAD

**Issue by leyangxing** [JusperLee/TDANet#26]
![image](https://github.com/user-attachments/assets/84613517-833c-430c-b84d-10bd2351bfcc)

![image](https://github.com/user-attachments/assets/bdfd389d-d543-426b-b48b-6ab3250f8e90)
![image](https://github.com/user-attachments/assets/c94ccfca-0f82-493c-bbf1-50d54c4b9f8d)

**Comment by leyangxing** [comment]
训练时的参数量是正确的：
![image](https://github.com/user-attachments/assets/c04ad595-ad7f-4a58-9dc3-0dff241c4ed4)

**Comment by JusperLee** [comment]
from ptflops import get_model_complexity_info

我一般使用这个库来计算可能是因为不同库对于不同操作的统计量是不一样。
