### ISSUE TITLE
cudnn加速不了

### ISSUE THREAD

**Issue by chai-xuan** [JusperLee/TDANet#29]
UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

**Comment by JusperLee** [comment]
这个应该是因为windows的原因

**Comment by chai-xuan** [comment]
大佬，我想询问一下，音频信号在输入网络的时候需要幅度归一化吗。我在做实验的时候发现，幅度似乎会影响模型的性能。

**Comment by chai-xuan** [comment]
我知道啦，soundfile在以float格式读取数据的时候会自动将音频数据归一化到-1和1的范围
