### ISSUE TITLE
MultiHeadAttention Input shape may be wrong

### ISSUE THREAD

**Issue by gongyuzhou** [JusperLee/TDANet#3]
Hi, 
I found that the code uses pytorch's nn.MultiheadAttention module, which demands the input shape [T, B, C], where T is sequence length and B is batch size. However the code's input shape of this part is [B, T, C].
This will make attention weights act on batch dimension, instead of time dimension.
I wonder if it is an error or not.

Thanks in advance
yuzhou

**Comment by JusperLee** [comment]
Hello Yuzhou.

I think you are right, it is a code error. When the dimensions are [B, T, C], the network treats the channels as batches, which would actually be equivalent to doing a linear extraction of the fused features. I designed this place to extract a global feature, so you are using appropriate MHA or other convolution operations.

I will subsequently modify and replace this part of the code with self.attn = ConvNorm(out_chan, out_chan, 3, bias=False). By experimenting on three datasets, this new attn module can get better results (relative improvement of 0.4 dB, smaller in parameters and computation).

Best wishes.
Kai.

**Comment by JusperLee** [comment]
The code is updated.
