### ISSUE TITLE
Loss选择

### ISSUE THREAD

**Issue by gnorZgnoD** [JusperLee/TDANet#37]
作者你好，我想问一下look2hear/matrix.py里的PairwiseNegSDR("sisdr")，SingleSrcNegSDR("sisdr")，MultiSrcNegSDR("sisdr")这三种sisdr有什么区别，用不同的sisdr测试出来会有区别吗，哪一种测出来最高呢
![image](https://github.com/user-attachments/assets/e0aef5de-8ff2-4bd5-b74c-39743fdfb4ef)

**Comment by JusperLee** [comment]
我们使用的就是snr
