### ISSUE TITLE
分离效果

### ISSUE THREAD

**Issue by WhiteChy** [JusperLee/TDANet#4]
你好，我在尝试复现您的tdanet但是效果都达不到文章里的表现，用的是 wsj02mix 和您[convtasnet](https://github.com/JusperLee/Conv-TasNet)的框架，尝试了论文里的参数和tdanet_best.py的默认参数，都效果不佳，SISDR只能达到8。在 asteroid 框架上效果也达不到文章表现。请问该怎么达到文章里的表现？

**Comment by JusperLee** [comment]
你好，

你可以尝试TDANet.py（这个与论文里一致）。

TDANet_best是我在之前的基础上搞了一个小计算量的版本，这个效果与TDANet.py几乎一致。

关于WSJ0-2Mix参数：
```yaml
out_channels=128,
in_channels=512,
num_blocks=16,
upsampling_depth=5,
enc_kernel_size=2,
num_sources=2,
sample_rate=8000,
```
欢迎再次尝试。我本人跑的是17.9 dB在210 epoch，理论上应该比这个更高（NUS的人跑过18.5左右）。
![image](https://user-images.githubusercontent.com/33806018/228730454-b4401e7a-3302-402b-abb0-f5f2bf9c22d7.png)

有问题再沟通。

祝好。

**Comment by JusperLee** [comment]
还有一种方式可以考虑将loss改成snr而不是sisnr。
