### ISSUE TITLE
请问 LRS2-2Mix 有speaker id 的信息吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [JusperLee/TDANet#7]
你好
      下载了您 的 lrs2_rebuild，没有发现metadata，不知道有没有speaker id的信息？谢谢！

**Comment by JusperLee** [comment]
文件名字就是spk1id_snr_spk2id_snr

但是没有更详细的信息，因为这些数据都是YouTube的，人工筛选很复杂

**Comment by JusperLee** [comment]
很抱歉我给你了一个错误的解释：

lrs2数据：例如：6300370419826092098_00007这个是一个speaker，这个6323221793324446979_00033是另一个speaker，中间0.20712和-0.20712是snr

**Comment by JusperLee** [comment]
> 

是的，这个就是LRS2数据集的原始内容。
