### ISSUE TITLE
Inquiry About Winning Model for Cinematic Sound Demixing Competition

### ISSUE THREAD

**Issue by owlwang** [JusperLee/TDANet#8]
Hi, I noticed that you won in this competition, I wonder if you used this codebase?
Will there be a relevant paper about the winning model?

[Cinematic Sound Demixing Track](https://www.aicrowd.com/challenges/sound-demixing-challenge-2023/problems/cinematic-sound-demixing-track-cdx-23/leaderboards)

**Comment by JusperLee** [comment]
This model is not TDANet. you can check the official published paper for details.

**Comment by owlwang** [comment]
Ok, Thanks~
